version: '3.9'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /php_crud
    entrypoint: "php -S 0.0.0.0:3000"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/php_crud
    depends_on:
      - db
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile.mysql
    restart: always
